### ISSUE TITLE
attribute class method doesn't work without a block

### ISSUE THREAD

**Issue by dgmora** [ElMassimo/oj_serializers#13]
I've noticed that if you have the following:

```ruby
class PostSerializer < Oj::Serializer
  attribute :title
end
```

You get an error:
```ruby
       undefined local variable or method `title' for #<PostSerializer:...>
     # (eval):9:in `render_as_hash'
     # /Users/david/.local/share/rtx/installs/ruby/3.0.5/lib/ruby/gems/3.0.0/gems/oj_serializers-2.0.3/lib/oj_serializers/serializer.rb:209:in `one_as_hash'
     # /Users/david/.local/share/rtx/installs/ruby/3.0.5/lib/ruby/gems/3.0.0/gems/oj_serializers-2.0.3/lib/oj_serializers/serializer.rb:169:in `render_as_hash'
```
This works fine if you have a block or you use attributes:
```ruby
# works
attribute :title do
 ...
end

# this works too
attributes :title
```

**Comment by ElMassimo** [comment]
Hi David!

Version 1 supported the following usage:

```ruby
attribute def title
  ...
end
```

You should use `attributes :title` instead.

---

Keeping this open as a reminder, because we could potentially support this use case as well, by extending [`attribute`](https://github.com/ElMassimo/oj_serializers/blob/main/lib/oj_serializers/serializer.rb#L414) to add a [`:method`](https://github.com/ElMassimo/oj_serializers/blob/main/lib/oj_serializers/serializer.rb#L582-L584) attribute instead of a [`:serializer`](https://github.com/ElMassimo/oj_serializers/blob/main/lib/oj_serializers/serializer.rb#L579-L581) attribute if a name is passed, and the method is not defined in the serializer.

**Comment by dgmora** [comment]
Do you think this should be part of compat? The error is a bit surprising
(not specific, maybe) since the method exists and can be used correctly if
there's a block provided
